name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run:
        
          # your ml workflow here
          pip install -r requirements.txt
          python train.py
          
          # Write your cml report
          echo "MODEL METRICS"
          cat metrics.txt 
